language: node_js
sudo: required
node_js:
  - "4"
script: npm test
services:
  - docker
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i -g npm@^3
    - npm install -g karma
    - npm install -g typescript
before_script:
    - npm install