language: node_js
node_js:
    - "0.10"
script: npm run test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g karma
    - npm install -g typescript
    - npm install -g typings
before_script:
    - npm install